package SINTAXIS;

public enum Token {

       RESERVADA,
        ASIGNACION,
        SUMA,
        RESTA,
        CADENA,
        CONSTANTE_ENTERA,
        CONSTANTE_DECIMAL,
        CONSTANTE_BOOLEANA,
        IDENTIFICADOR,
        MULTIPLICACION,
        DIVISION,
        IGUALACION,
        MOD,
        MAYOR,
        MENOR,
        MAYOR_IGUAL,
        MENOR_IGUAL,
        DIFERENCIA,
        AND,
        OR,
        EXCLAMACION,
        PUNTO_COMA,
        COMA,
        PUNTO,
        CORCHETEA,
        CORCHETEC,
        PARENTESISA,
        PARENTESISC,
        LLAVEA,
        LLAVEC,
        CORCHETES,
        LLAVES,
        PARENTESIS,
        ARROBA,
        NUMERAL,
        NUMERALES,
        ERROR,
        ERROR_DECIMAL
}
